// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXdliu47KdUM3xb26mgdOTWarsZ9CEkW8',
    appId: '1:270670165981:android:328527cd7b55490820a834',
    messagingSenderId: '270670165981',
    projectId: 'shave-f0ee7',
    databaseURL: 'https://shave-f0ee7-default-rtdb.firebaseio.com',
    storageBucket: 'shave-f0ee7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLz8M3uhwOE9rQ3v4GSyaIL43t6ronyT0',
    appId: '1:270670165981:ios:6de1604b521e40b420a834',
    messagingSenderId: '270670165981',
    projectId: 'shave-f0ee7',
    databaseURL: 'https://shave-f0ee7-default-rtdb.firebaseio.com',
    storageBucket: 'shave-f0ee7.appspot.com',
    iosClientId: '270670165981-qula46v6jc0tdlr36a4er1qn85r69lju.apps.googleusercontent.com',
    iosBundleId: 'com.example.barber',
  );
}
